accounts/urls.py
from django.urls import path
from accounts import views
app_name = "accounts" 
urlpatterns = [
    path("",views.index, name="index"),
    path("register/",views.register_account,name='register'),
    path("login/", views.login_account, name="login"),
    path("logout/", views.logout_account, name="logout"),
    path("profile/",views.profile_account,name="profile")
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("todo/", include('todo.urls')),
    path("accounts/",include('accounts.urls')),
    path('admin/', admin.site.urls),
]

todo/urls.py
from django.urls import path

from todo import views
app_name = "todo" 
urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add_todo, name='add_todo'),
    path("list/", views.list_todos, name="list_todos"),
    path("process/", views.process_data, name='process_data'),
    path("edit/<int:id>", views.edit_todo, name="edit_todo"),
    path("delete/<int:id>",views.delete_todo, name="delete_todo"),
    path("process_edit_todo/<int:id>",views.process_edit_todo,name="process_edit_todo"),
    path("filter/",views.filter_todo,name="filter_todo")
]

accounts/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Todo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE, related_name="todo", null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    due_date = models.DateTimeField(blank=True, null=True)
    priority = models.CharField(
        max_length=20,
        choices=[
            ('low','Low'),
            ('medium','Medium'),
            ('high','High'),
        ],
        default='medium'
    )


    def __str__(self):
        return self.title
    

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class RegistrationForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField()
    last_name = forms.CharField()

    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from accounts.forms import RegistrationForm
# Create your views here.

def index(request):
    return render(request, 'accounts/index.html')

def register_account(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("todo:index")
        else:
            print("form is not valid..")
    else:
        form = RegistrationForm()
    return render(request, 'accounts/register.html', {"form": form})

def login_account(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():
            user = form.get_user()
            print(user)
            login(request, user)
            return redirect("todo:index")
        else:
            print("form is not valid")
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {"form": form})

def logout_account(request):
    logout(request)
    return redirect("accounts:login")

@login_required
def profile_account(request):
    if request.user.is_authenticated:
        user = request.user
    else:
        user = None
    return render(request, "accounts/profile.html", {"user": user})

todo/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from todo.models import Todo
from datetime import datetime
# Create your views here.

@login_required
def index(request):
    context = {'message': "Application allows user to save their todos.."}
    return render(request, "todo/index.html", context)

@login_required
def add_todo(request):
    context = {"message": "Add your todo here.."}
    return render(request, "todo/add_todo.html", context)

def process_data(request):
    if request.method == 'POST':
        todo_title = request.POST.get("title")
        todo_description = request.POST.get("description")
        is_completed = False if request.POST.get("option_group") == 'no' else True
        created_at = datetime.now()
        updated_at = datetime.now()
        due_date = request.POST.get("dueDate")
        priority = request.POST.get('priority')
        todo_item = Todo(title = todo_title, description = todo_description, is_completed =is_completed,
                         created_at = created_at, updated_at = updated_at, due_date = due_date, priority = priority)
        todo_item.user = request.user
        todo_item.save()
        return HttpResponseRedirect(reverse("todo:list_todos"))
    else:
        pass
        

def list_todos(request):
    all_todos = Todo.objects.filter(user = request.user)
    context = {"all_todos": all_todos}
    return render(request, "todo/list_todos.html", context)

def edit_todo(request, id):
    todo_object = get_object_or_404(Todo, pk=id)
    return render(request, 'todo/edit_todo.html', {'todo_object': todo_object})

def process_edit_todo(request,id):
    print("In process edit todo...")
    todo_object = get_object_or_404(Todo, pk=id)
    if request.method == "POST":
        todo_object.title = request.POST.get('title')
        todo_object.description = request.POST.get("description")
        todo_object.is_completed = True if request.POST.get("option_group") == "yes" else False
        todo_object.due_date = request.POST.get("dueDate")
        todo_object.priority = request.POST.get('priority')
        todo_object.save()
    
    return HttpResponseRedirect(reverse("todo:list_todos"))

def delete_todo(request, id):
    todo_object = get_object_or_404(Todo, pk=id)
    todo_object.delete()
    return HttpResponseRedirect(reverse("todo:list_todos"))

def filter_todo(request):
    priority = request.GET.get('filter')
    if priority and priority!= "None":
        todo_object = Todo.objects.filter(priority=priority)
    else:
        todo_object = Todo.objects.all()
    return render(request, 'todo/list_todos.html',{"all_todos":todo_object})

accounts/templates/accounts/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {%block title%} {%endblock%}</title>
    {%block head%} {%endblock%}
</head>
<body>

    {%block content%}
    {%endblock%}
    
</body>
</html>

accounts/templates/accounts/index.html
{% extends 'accounts/base.html' %}

{% load static %}

{%block title %} {%endblock%}

{%block head%} 
    {{block.super}}
    <link rel="stylesheet" href="{% static 'accounts/css/index.css' %}">
{%endblock%}

{%block content%}

<h2>Welcome to Todo </h2>
<h3>Organize your tasks, stay productive.</h3>

<a href="{%url 'accounts:register' %}" class="button register-btn">Register </a> <a href="{%url 'accounts:login' %}" class="button login-btn"> Login  </a>

<p> Why todo ? </p>
<ol>
    <li> Simple & easy to use </li>
    <li> Track tasks and deadlines </li>
    <li> Stay on top of your goals</li>
</ol>

<p> New here ? <a href="{%url 'accounts:register' %}"> Register </a> Now and start managing your todos. </p>
<p> Already have an account? <a href="{%url 'accounts:login' %}">Login.</a> to continue.</p>


{%endblock%}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{%load static%}

{%block title%} Login Todo App {%endblock%}

{% block head %} 
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
{% endblock %}

{%block content%}
    
    <h2> Login </h2>
    <form method="post" id="login-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" id="loginButton">
            <span id="buttonText"> Login </span>
            <span id="loadingSpinner" style="display: none;">
                <i class="fa fa-spinner fa-spin"></i> 
            </span>
        </button>
    </form>

    <script src="{%static 'js/login.js' %}"></script>
{%endblock%}

accounts/templates/accounts/profile.html
{% extends "accounts/base.html"%}

{%block content%}

    {% if user %}
        <h2>Welcome {{user.first_name}} {{user.lastname}}</h2>
        <h3>Email: {{user.email}}</h3>
        <h3>UserName: {{user.username}}</h3>
        <a href="{% url 'accounts:logout'%}"> Logout </a>
    {% else %}
        <p>You are not logged in.</p>
        <a href="{% url 'accounts:login'%}">Login</a>
    {% endif %}


{%endblock%}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}

{%block content%}
    <h2> Register </h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
    </form>
{%endblock%}

todo/templates/todo/add_todo.html
{% extends 'todo/base.html'%}

{% load static %}

{% block title %} Add Todo. {% endblock %}

{% block head %} 
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'todo/css/add_todo.css' %}">
{% endblock %}

{% block content %}

    <h3> {{message}}</h3>

    <form id = "todoForm" action="{% url 'todo:process_data' %}" method="post">

        {% csrf_token %}
    
        <label for="title">Title</label>
        <input type="text" id="title" name="title" aria_invalid = 'true', aria-describedby="title-error">
        <span id="title-error"></span> 
        <br> <br>

        <label for="title">Description</label>
        <textarea id="description" name="description" rows="5" cols="30" placeholder="Enter your description here..."></textarea>
        <span id="description-error"></span>
        <br> <br>

        <label for="is_completed">Is completed</label>
        <input type="radio" id = "optionA" name="option_group" value="no" > No
        <input type="radio" id = "optionB" name="option_group" value="yes"> Yes
        <span id="option-group-error"></span>
        <br> <br>
        <label for ="dueDate">Due Date:</label>
        <input type="date" id="dueDate" name="dueDate" placeholder="YYYY-MM-DD">
        <span id = "due-date-error"></span>

        <br> <br>
        <label for="priority">Select the Priority..</label>
        <select id="priority" name="priority">
            <option value="" disabled selected>Select Priority</option>
            <option value="low">Low</option>
            <option value="medium">Medium</option>
            <option value="high">High</option>
        </select>
        <span id = "priority-error"></span>

        <br> <br>
        <input type="submit" value="Add" class="button-add">
        <input type="reset" value="Reset" class="button-clear">

    </form>

    <script src="{%static 'todo/js/validation.js' %}"></script>


{% endblock %}

todo/templates/todo/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}Todo Applications.. {% endblock %}</title>

    <link rel="stylesheet" href="{% static 'todo/css/styles.css' %}">

    {% block head %} {% endblock %}
</head>
<body>

    <h1> Welcome to To-do Application...</h1>

    {%block content%}
    {%endblock%}
    
</body>
</html>

todo/templates/todo/edit_todo.html
{% extends 'todo/base.html'%}

{%block content%}

<h5> Edit Your Todo...</h5>

{% if todo_object %}

<form action="{% url 'todo:process_edit_todo' todo_object.id%}" method="post">

    {% csrf_token %}

    <label for="title">Title</label>
    <input type="text" id="title" name="title" value="{{todo_object.title}}">
    <br> <br>

    <label for="title">Description</label>
    <textarea id="description" name="description" rows="5" cols="30" >{{todo_object.description}}</textarea>
    <br> <br>

    <label for="is_completed">Is completed</label>
    <input type="radio" name="option_group" value="no" {% if not todo_object.is_completed %} checked {% endif %}> No
    <input type="radio" name="option_group" value="yes" {% if todo_object.is_completed%} checked {% endif %}> Yes
    <br> <br>
    <label for ="dueDate">Due Date:</label>
    <input type="date" id="dueDate" name="dueDate" value="{{todo_object.due_date|date:'Y-m-d'}}">

    <br> <br>
    <label for="priority">Select the Priority..</label>
    <select id="priority" name="priority">
        <option value="low" {% if todo_object.priority == "low" %} selected {% endif %}>Low</option>
        <option value="medium" {% if todo_object.priority == "medium" %} selected {% endif %}>Medium</option>
        <option value="high" {% if todo_object.priority == "high" %} selected {% endif %}>High</option>
    </select>

    <br> <br>
    <input type="submit" value="Update">
    <input type="reset" value="Reset">

</form>

{%else %} 

{%endif%}

{% endblock %}

todo/templates/todo/index.html
{% extends 'todo/base.html'%}

{% block content %}

    {%load static%}

    <h5> This applications allows the user to create todos. </h5>

    <a href="{% url 'todo:add_todo' %}" class="button-create"> Create Todo. </a> 
    <a href="{% url 'todo:list_todos' %}" class="button-show"> Show Todos. </a>

    <br> <br>

    <a href="{% url 'accounts:logout' %}" class="button-logout" id = "account-logout"> Logout </a>
    <a href="{% url 'accounts:profile' %}" class="button-view-profile" > Profile </a>

    <div id="confirmModal" class="modal">
        <div class="modal-content">
            <p>You are about to be logged out from the application?</p>
            <div class="modal-actions">
                <button id="confirmYes">Yes</button>
                <button id="confirmNo">No</button>
            </div>
        </div>
    </div>

    <script src="{%static 'todo/js/index.js' %}"></script>



{% endblock %}

todo/templates/todo/list_todos.html
{%extends "todo/base.html"%}

{% load static %}

{%block title%} List Todos. {%endblock%}


{% block head %} 
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'todo/css/list_todo.css' %}">
{% endblock %}


{%block content%}

    {% if all_todos %}
        <h5> Your Listed todos...</h5>
        <form action = "{% url 'todo:filter_todo' %}" method="get">
        <label for="Filter">Filter Todo By Priority </label>
        <select id="filter" name="filter">
            <option value="None" selected>None</option>
            <option value="low">Low</option>
            <option value="medium">Medium</option>
            <option value="high">High</option>
        </select>
        <button type="submit" class="button-apply">Apply</button>
        </form>
        <br> <br>
        <table>
            <tr>
            <th> No# </th> <th> Created By </th> <th> Title </th> <th> Description </th> <th> Is_completed </th> <th> Priority </th> <th colspan="2"> Actions</th>
            </tr>
            {% for todo in all_todos %}
                <tr>
                    <td>{{forloop.counter}}</td> <td> {{todo.user.username}} </td> <td>{{todo.title|truncatechars:10}}</td> <td>{{todo.description|truncatechars:20}}</td> <td>{{todo.is_completed|yesno:"Completed, Pending"}}</td> 
                    <td>{{todo.priority}}</td> <td> <a href="{% url 'todo:edit_todo' todo.id %}" class="button-edit"> Edit </a> </td> 
                    <td> <a href="{% url 'todo:delete_todo' todo.id %}" class="button-delete"> Delete </a></td>
                </tr>
            {% endfor %}
        
        </table>
    {%else %}
        <h3> No todos found </h3>
        <a href="{%url 'todo:add_todo'%}"> Create One.</a>
    
    {%endif%}
    <br>

    <a href="{% url 'todo:index' %}" class="button-create">Go Back</a>

    <script src="{% static 'todo/js/list.js' %}"></script>

{% endblock %}